@startuml MVC

top to bottom direction
skinparam packageStyle rectangle
hide empty members

package "Vistas" {
  class SolicitudesView
}

package "Controladores" {
  class RecibirSolicitudController
  class RecibirFormularioController
}

package "Modelos" {
  class Solicitud
  class Formulario
  class CorreoRecibido
}

@enduml